version: '3'

services:
  api:
    build: .
    command: "python3 app.py"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    ports:
      - "3000:3000"

  client:
    build: client
    command: "npm start"
    ports:
      - '3001:3001'
    links:
      - api
    depends_on:
      - api