name: Develop Workflow

on:
  push:
    branches: [ "develop" ]
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      IMG_VERZN: '0.9.0'

    steps:

    - name: checkout main branch from Github
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install flake8

    - name: Running linting tests
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Increment Semantic Version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: $IMG_VERZN
        version-fragment: 'major'

    - name: Build Backend image
      run: |
        docker build -t ${{secrets.DOCKERHUB_USERNAME}}/blackjack-backend:v${{ steps.bump_version.outputs.next-version }}  .
        docker run -d --name backend -p 3000:3000 ${{secrets.DOCKERHUB_USERNAME}}/blackjack-backend:v${{ steps.bump_version.outputs.next-version }}  .


    - name: Run Smoke Tests on Backend
      run: echo smoke tests

    - name: Build Frrontend Image
      run: |
        docker build -t ${{secrets.DOCKERHUB_USERNAME}}/blackjack-frontend:v${{ steps.bump_version.outputs.next-version }}  client/
        docker run -d --name frontend -p 3001:3001 ${{secrets.DOCKERHUB_USERNAME}}/blackjack-frontend:v${{ steps.bump_version.outputs.next-version }}

    - name: Run Smoke Tests on Frontend
      run: echo smoke tests

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: '${{secrets.DOCKERHUB_USERNAME}}'
        password: '${{secrets.DOCKERHUB_TOKEN}}'

    - name: Push images to docker hub
      run: |
        docker push ${{secrets.DOCKERHUB_USERNAME}}/blackjack-backend:v${{ steps.bump_version.outputs.next-version }}
        docker push ${{secrets.DOCKERHUB_USERNAME}}/blackjack-frontend:v${{ steps.bump_version.outputs.next-version }}