name: Develop Workflow

on:
  push:
    branches: [ "feature" ]
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      IMG_VERZN: '1.0.0'

    steps:

    - name: Running progression tests on feature
      run: echo tests are awesome

    - name: Increment Semantic Version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: '$IMG_VERZN'
        version-fragment: 'major'